### ISSUE TITLE
Custom themes/MSStyles don't switch correctly

### ISSUE THREAD

**Issue by shadeMe** [AutoDarkMode/Windows-Auto-Night-Mode#124] opened 2020-07-06 10:53 UTC
**Describe the bug**
When the app triggers a switch to a theme that uses a custom MSStyle, several UI elements do not update to the new style after the automatic switch. My current setup has two custom themes - Light (based on the default Aero MSStyle) and Dark (based on this [custom MSStyle](https://www.deviantart.com/niivu/art/Dracula-for-Windows-10-843182521)). The bug occurs regardless of the direction of the switch, i.e., light to dark or vice-versa.

**To Reproduce**
1. Setup two themes, one based on Aero and another based on the above linked MSStyle.
2. Trigger the switch.

**Expected behavior**
All UI elements have their styles updated.

**Screenshots**
Bug:
![Capture](https://user-images.githubusercontent.com/214450/86585618-072b7480-bf87-11ea-819b-6d2d5271c5b1.JPG)

Expected:
![Capture](https://user-images.githubusercontent.com/214450/86586059-9e90c780-bf87-11ea-9f97-864714622d24.JPG)

**Environment:**
 - OS Version: Windows 1909
 - Auto Dark Mode version number 2.4 RC1
 - Do you use Windows .theme switcher? Yes
 - Has user admin rights? yes
 - which antivirus software you use? None
 - what language is your Windows set to? English

**Additional context**
This issue _does not_ occur if I manually "open" the saved theme files in `AppData\Local\Microsoft\Windows\Themes`. Perhaps you need to use a shell method (ShellExecute) to do the switch? One side-effect of opening the themes thus is that the Personalization settings applet automatically pops up afterwards.

**Comment by Spiritreader** [comment] 2020-07-06 11:22
This is possibly fixed in versionX due to ThemeHandler spawning its own thread with STA apartment state for com interaction.

Will get back to you as soon as testing begins.

**Comment by shadeMe** [comment] 2020-07-06 13:15
> 
> 
> This is possibly fixed in versionX due to ThemeHandler spawning its own thread with STA apartment state for com interaction.
> 
> Will get back to you as soon as testing begins.
> 
> Update: Actually, could we link up via the autodarkmode telegram group? I can provide you with a preview build of vX.

Okay, I've joined the group.

**Comment by Spiritreader** [comment] 2020-07-06 14:17
I've confirmed with @shadeMe that this works in versionX,

**Comment by Armin2208** [comment] 2020-07-06 14:37
Armin also confirmed this xD

**Comment by tejasetty** [comment] 2020-10-06 14:24
Hello! Was this issue fixed? If yes, then in which version? Since still i am facing with themes. dark theme not applying properly i.e. most of the elements belongs to light theme. I had observed that its just changing light theme into black. I can provide you more details if required.

**Comment by Armin2208** [comment] 2020-10-06 14:31
Will be fixed with version 10, beta is coming in in 1 - 2 weeks here on github :)

**Comment by tejasetty** [comment] 2021-05-03 13:37
> Will be fixed with version 10, beta is coming in in 1 - 2 weeks here on github :)

not sure when beta will come. it has been more than 6 months

**Comment by Armin2208** [comment] 2021-09-05 13:18
Auto Dark Mode X fixes this issue, coming at 5th october 2021.

**Closed by Armin2208** 2021-09-05 13:18 UTC
Labels: bug, version X

**Comment by tejasetty** [comment] 2021-09-05 13:21
> Auto Dark Mode X fixes this issue, coming at 5th october 2021 alongside with Windows 11.

Can I have access to early version?

**Comment by Spiritreader** [comment] 2021-09-05 16:54
> > Auto Dark Mode X fixes this issue, coming at 5th october 2021 alongside with Windows 11.
> 
> Can I have access to early version?
we have dev builds available here:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode#telegram-group

**Comment by Armin2208** [comment] 2021-09-05 17:50
Although @Spiritreader hates me:
Here is a leaked version of Version X Beta 4
[](https://www.mediafire.com/file/9xu8wfb3zu2h8v5/AutoDarkModeX_Setup_20212307_1741.exe/file)
