### ISSUE TITLE
[Feature request] Execute other applications after the trigger takes effect

### ISSUE THREAD

**Issue by ddayzzz** [AutoDarkMode/Windows-Auto-Night-Mode#322] opened 2021-10-18 14:12 UTC
**Execute other applications after the trigger takes effect**. For example, I am working on thrid monitor and I have to run the monitor manager (it provide CLI) to modify comfortable brightness at sunset or sunrise. Fortunately, I find this great job and I want to automatically change the brightness as soon as Windows theme color changed which is triggered by this app when conditions met. I conclude: **auto-dark-mode -> tigger -> theme changed -> call third-part app by preconfigured settings -> finish**

**Comment by Spiritreader** [comment] 2021-10-18 22:40
Thank you so much for giving us your feedback. While we'll continue to use feedback to guide the future of features like this, currently Auto Dark Mode has no plans to support custom triggers and/or scripts.

Duplicate of #186.

**Closed by Spiritreader** 2021-10-18 22:40 UTC
Labels: enhancement
