### ISSUE TITLE
Auto mode for Accent Color for title bars and window borders

### ISSUE THREAD

**Issue by 13xforever** [AutoDarkMode/Windows-Auto-Night-Mode#682] opened 2023-01-31 14:36 UTC
**Describe the enhancement or feature you'd like**
I'm not sure what the rationale was behind the manual selection of how accent color is applied for this setting, but to have proper behavior that's matching windows, you need to use Light theme mode for Light theme, and Dark theme for Dark theme (duh).

Right now, some parts of the UI will have wrong colors if this option is used (like no contrast between the menu and content controls, or title bar/tab colors in Edge, etc).

**Describe alternatives you've considered**
There should be an Auto option and it should be the default, as it matches the behavior of manually switching the Light/Dark mode in Windows Settings.

Currently leaving Accent Color for title bars in ADM settings will preserve Accent color preference in Windows Settings when switching themes, which is the desirable behavior, but it's not obvious, so adding a note describing expected behavior is an alternative.

**Additional context**
Correct Dark/Dark combo:
![image](https://user-images.githubusercontent.com/36445/215789079-5fb28398-11d6-4864-9660-cb3fffd6bf9f.png)

Wrong Dark/Light combo:
![image](https://user-images.githubusercontent.com/36445/215789202-ddc9e931-adda-40fa-8491-047d28d40acd.png)

Correct Light/Light combo:
![image](https://user-images.githubusercontent.com/36445/215789356-e366e003-c8ca-43b0-bc34-0403817ccb66.png)

Wrong Light/Dark combo:
![image](https://user-images.githubusercontent.com/36445/215789504-6a20f1ea-d680-4fec-85c5-5e28ca88eec5.png)

**Comment by Spiritreader** [comment] 2023-02-03 02:31
> I'm not sure what the rationale was behind the manual selection of how accent color is applied for this setting, but to have proper behavior that's matching windows, you need to use Light theme mode for Light theme, and Dark theme for Dark theme (duh).

> There should be an Auto option and it should be the default, as it matches the behavior of manually switching the Light/Dark mode in Windows Settings.

The rationale is pretty simple. In its most basic configuration ADM should only modify the System/App's light and dark theme, nothing more.
This is why we give users an option to turn that option on *and* specify whether they want an accent color during their specified day or night time. There isn't supposed to be an auto mode. It's more likely that this is a wording issue. The checkbox should probably say 

"Accent color for title bars and window borders **during**" 

instead, which makes it more clear what the setting is supposed to do.

> Right now, some parts of the UI will have wrong colors if this option is used 

The images you're seeing with the UI having incorrect Mica DWM window states isn't supposed to happen. This seems to be a frontend bug or an issue with registry key event watchers. It would be awesome if you could describe how that happened and provide some guidance on how to reproduce it. Because I can't on my test machines.

The origin why this occurs in the first place is that our window framework doesn't support Mica titlebars due to an issue with overlapping control buttons (minimize, maximize, close). 
As such, we have to use the default DWM titlebar and remove the base layer background from the app in order to fully fake a MIcah transparent window with WPF.  And in reverse then put an overlay over the titlebar and add a background base layer to the navigtion menu and page section.

Our UI thus needs to be aware when users toggle the accent color for titlebars setting. Once it receives such an event (via registry hive monitoring) it checks whether the accent color for titlebars was enabled/disabled and redraws the interface according to specification. The only instance where I've seen this potentially fail so far is on ARM systems without x86 emuilation, but I most likely missed something here.

> Currently leaving Accent Color for title bars in ADM settings will preserve Accent color preference in Windows Settings when switching themes, which is the desirable behavior, but it's not obvious, 

This is actually sort of a Windows bug because on 11 22H2 a DWM refresh is required for the changes to take effect, but there is no API to trigger that refresh unless a full theme switch (from light to dark or vice versa) is performed, because then internally a DWM refresh appears to be triggered. On 11 22H1 and below it works as intended.
We also already have this mentioned in our FAQ about limitations: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Known-limitations#windows-11-22h2
We could add a hover text stating something like "Will only show after a theme switch on Windows 11 22H2 and up" to make it more clear what will happen.

**Comment by 13xforever** [comment] 2023-02-03 02:40
To reproduce the behavior, I have simply toggled the Light/Dark theme radio buttons under the Accent Color for title bars checkbox, nothing more, and it's 100% reproducible here.

In case this is relevant, I'm on Win11 22H2 and have HDR enabled.

Why I perceive current behavior as wrong, is because the checkbox right above it, the Accent Color for Taskbar behaves as a toggle that explicitly checks/unchecks the corresponding setting in Windows Settings, however Accent Color for title bars behaves differently.

And yeah, from the wording in FAQ it's not obvious when exactly the issue occurs, as I expect that switching Light/Dark mode is effectively changing the theme (as it does in Windows Settings).

**Comment by Spiritreader** [comment] 2023-02-03 14:21
I found a way to counteract the issue for now and pushed a fix to the latest beta.
That should resolve the UI issue and also make the experience consistent across all Windows versions.

Please check it out.

**Comment by 13xforever** [comment] 2023-02-04 05:13
I think wording it "only during" ... theme would make it clearer.
The behavior is consistent with the Windows Settings toggle, except for the title bat theming in ADM, which you mentioned is specific to the WPF framework you're using.

I've attached steps recorder screenshots with some comments, mostly for historical documentation of current behavior
[accent color for title bars.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/10607724/accent.color.for.title.bars.zip)

**Comment by Spiritreader** [comment] 2023-02-04 11:11
Ah yes there was something that I had optimized away unsuccessfully which caused it to break.
Should be fixed now.

The flashing is normal because the theme switch lags a bit, but this won't happen during a normal theme switch, just when toggling the setting from within ADM.

https://user-images.githubusercontent.com/18438899/216764017-1b23fdba-7c46-4c6c-8537-d2dcaec4bde1.mp4

**Comment by Spiritreader** [comment] 2023-04-26 18:46
DWM refreshing has been advanced a bit further and this issue should now no longer occur, except when there are ManagementEvent errors related to registry key watching.

Please reopen if the issue still occurs on beta versions 10.3.1.42 and up.

**Closed by Spiritreader** 2023-04-26 18:46 UTC
Labels: enhancement
