### ISSUE TITLE
Wallpaper changes to black when switching modes

### ISSUE THREAD

**Issue by filipkamenski** [AutoDarkMode/Windows-Auto-Night-Mode#550] opened 2022-10-13 14:12 UTC
### Description

Wallpaper changes to black when switching modes. Both pick a wallpaper and pick a theme options under personalization are turned off. 

### Expected Behavior

adm should not change the wallpaper.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9777514/service.log)
[config.yaml.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9777530/config.yaml.log)

### Operating System

windows 11 build 22623.741

### Commit Hash and Version

- Commit: `db03953`
- Service: `10.3.0.37`
- Updater: `2.5.1`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.7`

### Screenshots

![image](https://user-images.githubusercontent.com/71707405/195620762-5ac5371f-495a-4202-9ea8-613108de9dbe.png)

**Comment by filipkamenski** [comment] 2022-10-13 14:15
Forgot to mention that i use Windows spotlight (the build in feature)  for wallpapers

**Comment by filipkamenski** [comment] 2022-10-13 15:59
![image](https://user-images.githubusercontent.com/71707405/195646611-91e38379-d329-49b8-984c-fedf82617e9b.png) 
I just discovered that it changes the accent color to manual black too.

**Comment by Spiritreader** [comment] 2022-10-13 16:37
duplicate of #547

**Closed by Spiritreader** 2022-10-13 16:37 UTC
Labels: bug
