### ISSUE TITLE
Auto dark mode based on brightness

### ISSUE THREAD

**Issue by nitro122** [AutoDarkMode/Windows-Auto-Night-Mode#855] opened 2024-06-05 11:30 UTC
**Describe the enhancement or feature you'd like**
if there was a way in which dark mode would be toggled based on display brightness intensity 
For instance  I would set an brightness intensity at which darkmode is toggled 
**Describe alternatives you've considered**
none so far as i think autodarkmode already covers everything else perfectly

**Additional context**
So I have a mac that dual boots with windows. However, on macOS there is similar software to autodarkmode, called "Dynamic Dark mode". It has the feature this feature which I feel is makes toggling the dark mode so much more convenient I've add a screenshot of the program to better represent the feature 

![Screenshot 2024-06-05 at 1 29 36 PM](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/167356796/1869c5a6-a8ae-44db-aac0-10fd020077bb)

**Comment by Armin2208** [comment] 2024-06-06 17:41
Yes, I once wanted to add this, but I had't time yet :D

**Comment by Spiritreader** [comment] 2024-11-24 23:18
yes, duplicate of #15, closing in favor of retaining order.

**Closed by Spiritreader** 2024-11-24 23:18 UTC
Labels: enhancement
