### ISSUE TITLE
Add the ability to control Windows Night Light from ADM

### ISSUE THREAD

**Issue by sripadks** [AutoDarkMode/Windows-Auto-Night-Mode#859] opened 2024-06-24 18:36 UTC
It would be cool to have the feature/setting to control Windows Night Light from ADM.

Night Light only has two options. Either give Windows your location (not preferable due to privacy concerns) or manually set time. While with manual time setting everyday the sunset and sunrise changes can be approximated, it is a hassle to set the times manually when seasons change or are changing.

So it would be dope if ADM had its own version of Night Light (à la f.lux) over which it has complete control or had the ability to control Windows Night Light because ADM has more options and is more privacy friendly.

**Comment by Armin2208** [comment] 2024-06-24 22:15
duplicate of  #85 

We whish to implement this, but its currently not possible.

**Closed by Armin2208** 2024-06-24 22:15 UTC
Labels: enhancement

**Comment by sripadks** [comment] 2024-06-25 01:31
Thanks! Sorry for the duplicate. I did check the open issues and couldn't find this. My bad. Cheers.
