### ISSUE TITLE
Auto Dark Mode changes only Windows mode and resets wallpaper and accent color

### ISSUE THREAD

**Issue by ZMYaro** [AutoDarkMode/Windows-Auto-Night-Mode#547] opened 2022-10-11 01:35 UTC
### Description

Recently, when Auto Dark Mode changes my theme to dark, it has been switching the Windows mode to dark, but the app mode is light.  It also changes my wallpaper to solid black and my theme color to gray. So far, it seems to stop happening when I disable ADM, so I am inclined to think it is ADM causing it, and not only an issue in Windows, but I _am_ on the Windows and ADM beta channels.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9750268/service.log)
[config.yaml](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9750276/config.txt)

### Operating System

Version 22H2 build 22623.741

### Commit Hash and Version

- Commit: `69a0702`
- Service: `10.3.0.31`
- Updater: `2.5.1`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.7`

**Comment by Spiritreader** [comment] 2022-10-11 09:22
Thanks for turning this into a desperate issue.. 

As I mentioned in the other thread I would require some more data to look into this. 

Which would be the debug mode enabled and you setting up your theme / desktop while auto dark Mode is off and then posting the full theme file here. 

The logs with debug enabled will reveal what theme is applied during synchronization, and once I have the theme file I can attempt to reproduce the issue. 
Thanks!

**Comment by Spiritreader** [comment] 2022-10-11 09:22
Thanks for turning this into a desperate issue.. 

As I mentioned in the other thread I would require some more data to look into this. 

Which would be the debug mode enabled and you setting up your theme / desktop while auto dark Mode is off and then posting the full theme file here. 

The logs with debug enabled will reveal what theme is applied during synchronization, and once I have the theme file I can attempt to reproduce the issue. 
Thanks

**Comment by albertopasqualetto** [comment] 2022-10-12 14:16
That also happens to me.

1. Default theme: [Roamed.theme.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9765650/Roamed.theme.txt)
2. Theme forced dark with ADM
3. Theme non-forced dark with ADM
4. Custom theme corrected while ADM on light mode:[Custom.theme.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9765655/Custom.theme.txt)
5. Theme forced dark with ADM. ADMTheme: [ADMTheme.theme.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9765673/ADMTheme.theme.txt)

Config: [config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9765686/config.yaml.txt)
Debug logs: [service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9765689/service.log)

**Comment by albertopasqualetto** [comment] 2022-10-13 06:32
@Spiritreader I already posted my Roamed.theme, and also that has not a background set.
My background is a solid green one from windows's selector.
I see that today light mode was set with ADMTheme (and black background).

**Comment by Spiritreader** [comment] 2022-10-13 07:53
Oh sorry I some how missed that, am a bit in a hurry lately.
I know what's happening now, the section that parsed the background does not get read properly. That shouldn't be too hard to fix, I'll update you with a new beta build as soon as I've looked at the code responsible for reading the background color.

**Comment by Spiritreader** [comment] 2022-10-13 16:41
@albertopasqualetto I've pushed a new beta build (10.0.1.38) which addresses your issue and should also lessen the number of cases where ADM incorrectly set a black wallpaper

**Comment by amitaba** [comment] 2022-10-15 16:06
Same issue: I had a dark gray solid background, now as soon as Dark mode switches on the background is set to Black. Latest build running on Windows11Pro x64 22H2.

**Comment by Spiritreader** [comment] 2022-10-15 18:04
> Same issue: I had a dark gray solid background, now as soon as Dark mode switches on the background is set to Black. Latest build running on Windows11Pro x64 22H2.

I assume you are on the latest beta now, please post your log and config file again so I can take a look.
I am unable to reproduce this on 10.3.0.46.

https://user-images.githubusercontent.com/18438899/196001606-ce8dfc1c-91a9-481d-84a7-399c2dc0dfae.mp4

**Comment by Spiritreader** [comment] 2022-10-18 11:43
> I cannot find beta 10.3.0.46 - I have set Beta channel in Settings, clicked on Check for Updates, it keeps saying 10.2... is latest build. I have searched the repo but cannot find a beta channel for installs, only the current (11 builds) for release versions.

Usually we have this sort of reports from people that live in China, as the gfw blocks raw.githubusercontent.

You can find and download builds manually here.
https://github.com/AutoDarkMode/AutoDarkModeVersion/releases

**Comment by Spiritreader** [comment] 2022-11-02 13:24
Wallpaper resets have been addressed in 10.3 as best as possible.
There are still a few limitations that might cause this behavior, please see our list of known limitations here:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Known-limitations

if you feel like none of these conditions apply, please let us know.

**Closed by Spiritreader** 2022-11-02 13:24 UTC
Labels: bug
