### ISSUE TITLE
Add autoswitch darl/light themes

### ISSUE THREAD

**Issue by SlimRG** [AutoDarkMode/Windows-Auto-Night-Mode#208] opened 2021-02-16 11:39 UTC
When windows switches to light/dark mode console doesn't have settings to switch theme.

**Comment by Armin2208** [comment] 2021-02-16 13:05
console?

**Comment by avi12** [comment] 2021-02-18 14:04
I believe he means PowerShell and/or Command Prompt
If so, it's up to Microsoft to add support for OS-based theme switching, and I believe that if it is added, it will be to [Windows Terminal](https://github.com/Microsoft/Terminal)

**Comment by emberaholdon** [comment] 2021-02-19 00:35
> When windows switches to light/dark mode console doesn't have settings to switch theme.

Command prompt would be doable, see: https://github.com/Armin2208/Windows-Auto-Night-Mode/issues/121
PowerShell does not matter that much imho, because it is blue which goes nicely with both color scheme.

**Comment by Armin2208** [comment] 2021-10-12 23:44
duplicate of #121

**Closed by Armin2208** 2021-10-12 23:44 UTC
Labels: enhancement
