### ISSUE TITLE
[Feature request] Theme toggle based on light detection

### ISSUE THREAD

**Issue by avi12** [AutoDarkMode/Windows-Auto-Night-Mode#890] opened 2024-11-24 14:18 UTC
**Describe the enhancement or feature you'd like**
Using the time as an anchor is great, but he doesn't quite take into account whether changes
Using the light levels that the webcam can detect to determine whether the room is too dark for the computer to have light mode is a better take, assuming of course that enough light reaches the room during daylight to begin with

**Describe alternatives you've considered**
There aren't any alternatives as far as I'm aware, it's only using time anchors

**Comment by Spiritreader** [comment] 2024-11-24 23:19
duplicate of #15, is planned (with ambient sensor, because webcam requires some computer vision and is a potential privacy nightmare), but currently not realistic as the amount of work-hours required exceeds the available dev-hours for this project

**Closed by Spiritreader** 2024-11-24 23:19 UTC
Labels: enhancement
