### ISSUE TITLE
"enable dark mode when device is unplugged" toggles to dark at 100%, while still plugged

### ISSUE THREAD

**Issue by giaaaacomo** [AutoDarkMode/Windows-Auto-Night-Mode#585] opened 2022-10-26 13:16 UTC
i bet that there is something going on with the policy that stops the device charging at full battery level

**Comment by Spiritreader** [comment] 2022-10-26 14:24
duplicate of #386 and https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Troubleshooting

**Closed by Spiritreader** 2022-10-26 14:24 UTC
