### ISSUE TITLE
File Explorer

### ISSUE THREAD

**Issue by udobehm** [AutoDarkMode/Windows-Auto-Night-Mode#498] opened 2022-08-26 07:03 UTC
### Description

Hey, sometimes the Windows File Explorer in the 22H2 Build doesn't switch correctly from day to night mode or vice versa. Have you experienced this issue and are you working on a solution for that?

Thanks - Udo

### Log Data

[AutoDarkMode.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9430596/AutoDarkMode.zip)

### Operating System

Win 11 22H2

### Commit Hash and Version

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

### Screenshots

![image](https://user-images.githubusercontent.com/50866188/186842343-8ffbb3b2-b487-41e6-b206-9fee42aa8d5c.png)
should be in light mode, the Explorer... didn't switch correctly

**Comment by cyxnzb** [comment] 2022-08-26 10:32
Yeah,the same question i have in Windows 11 dev build 25188

**Comment by litbeep** [comment] 2022-09-01 17:57
Yep. Same issue here. Switching between light/dark from the Settings app works fine, but not when the change is applied through Auto Dark Mode.

**Comment by smallyoung1** [comment] 2022-09-02 10:38
Same problem
But I will use task manager to restart file explorer to solve the problem.

**Comment by Armin2208** [comment] 2022-09-02 17:45
> Same problem But I will use task manager to restart file explorer to solve the problem.

fortunately the task manager switches theme just fine

**Comment by SnowVolf** [comment] 2022-09-04 15:30
Same problem, Win11 Pro 22622.690

**Comment by Spiritreader** [comment] 2022-09-05 22:12
duplicate of #424

**Closed by Spiritreader** 2022-09-05 22:12 UTC
Labels: bug
