### ISSUE TITLE
Add more blur on transparent area

### ISSUE THREAD

**Issue by diego-gz** [AutoDarkMode/Windows-Auto-Night-Mode#279] opened 2021-10-06 11:18 UTC
I think this app should **_blur_** the transparent background more so it matches with the _native_ Bindows 11 apps.

Current App
![image](https://user-images.githubusercontent.com/83010300/136192226-f757eecf-1ead-400c-861b-901f18a20e9f.png)

Native Windows app example:
![image](https://user-images.githubusercontent.com/83010300/136192620-d1526a64-310f-4a6c-adda-1472e456915a.png)

**Comment by Spiritreader** [comment] 2021-10-06 11:30
Duplicate of #139

**Closed as completed by Spiritreader** 2021-10-06 11:30 UTC
