### ISSUE TITLE
Daylight savings time issue

### ISSUE THREAD

**Issue by weberjam007** [AutoDarkMode/Windows-Auto-Night-Mode#434] opened 2022-03-13 10:39 UTC
**Description**

The light mode was set an hour early and dark mode is listed as an hour early for today. I believe this is due to daylight savings time starting here in the US.

**Expected behavior**

I expected the change to be at 7:16 am here in Philadelphia, PA but it changed at 6:16 am (as listed in the software).

**Log Data**

[AutoDarkMode_config_service_20221303.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8239346/AutoDarkMode_config_service_20221303.zip)

**Commit Hash and Version**

- Commit: `5e6ea8a`
- Service: `10.1.0.10`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Screenshots**

I believe these are an hour off due to daylight savings time:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/36638740/158055500-8a751b2b-4710-4026-a1fe-b535f646bf79.png">

These should be the correct times:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/36638740/158055555-45dcc667-5b36-4142-b72f-b0879f6d319e.png">

**Comment by Spiritreader** [comment] 2022-03-13 11:06
location data takes 24h to update

**Comment by derekschinke** [comment] 2022-03-13 23:09
Same issue in CDT in Chicago. Switching time setting doesn't work.

**Comment by Spiritreader** [comment] 2022-04-25 11:45
Since no one reported back on this, I assume that this was about 24h update times for location.
I'll close this for now, as it appears everything is working as intended, just sometimes missing one switch depending on when exactly the location module updates.

**Closed by Spiritreader** 2022-04-25 11:45 UTC
Labels: bug
