### ISSUE TITLE
Feature request about autodarkmode

### ISSUE THREAD

**Issue by Gaoyifei1011** [AutoDarkMode/Windows-Auto-Night-Mode#356] opened 2021-11-05 16:07 UTC
1.Hope to improve the application interface.
希望能够改进应用界面。

At present, the interface of Autodarkmode application is the mode of Windows 10 UI interface, hope to upgrade to Windows 11 style in the next version, it would be better if you can use Win UI2.7 or Win UI3.
目前Autodarkmode应用的界面是Windows 10 UI界面的模式，希望在接下来的版本中升级为Windows 11风格的样式，如果能够使用Win UI2.7或Win UI3就更好了。
![图片](https://user-images.githubusercontent.com/49179966/140539930-f5aa300e-941d-41eb-bdf2-2d5696f731cd.png)

2.Taskbar right-click menu issues
任务栏右键菜单的问题
We want to upgrade the taskbar right-click menu style to Win UI and add multilingual support for taskbar right-click menu
希望能够将任务栏右键菜单的样式提升为Win UI并且添加任务栏右键菜单的多语言支持
![图片](https://user-images.githubusercontent.com/49179966/140539885-5322c450-988d-4cba-8093-0e5016adebfe.png)

3.Hope to add the MSIX installation package
希望添加MSIX安装包。
At present, we only see the installation package in the traditional EXE format in the release interface. We hope to add support for the MSIX installation package in the future version.Ability to install the Installer from the command line or desktop App and uninstall it from the Start menu with one click.
目前仅在release界面中看见了传统exe格式的安装包，希望在未来版本中能够添加msix安装包的支持。能够一键通过命令行或desktop app installer安装和在开始菜单中一键卸载。

**Comment by Spiritreader** [comment] 2021-11-05 18:56
For issue 1, duplicate of #297.
For issue 2, duplicate of #287.
For issue 3, duplicate of #195.

**Closed by Spiritreader** 2021-11-05 18:56 UTC
Labels: enhancement
