### ISSUE TITLE
App crashes after pressing copy button

### ISSUE THREAD

**Issue by 5idereal** [AutoDarkMode/Windows-Auto-Night-Mode#382] opened 2021-11-24 19:00 UTC
**Description**

Using Windows 11 Build 22000.348.

Click the copy button on about page.

**Expected behavior**

The app crashes. As the gif below.

**Log Data**

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7598130/service.log)
[config.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/7598131/config.txt)

**Commit Hash and Version**

![image](https://user-images.githubusercontent.com/30827929/143297970-6cce7ed6-5c31-4603-b751-64ab201c6206.png)

**Screenshots**

![age](https://user-images.githubusercontent.com/30827929/143297946-f26caf2f-c9e4-4c2f-8121-f0d0b05ed5a7.gif)

**Comment by Spiritreader** [comment] 2021-11-25 01:00
I can't reproduce this. I've added exception handling for this in the latest build, please update.
An error message should occur in the UI. Please post a screenshot of that.

**Comment by SiderealArt** [comment] 2021-11-25 11:38
The time it takes for the app to crash became longer.

![age](https://user-images.githubusercontent.com/30827929/143434734-d5de487b-fcb2-4657-a5e7-94b527fdecd9.gif)

**Comment by Spiritreader** [comment] 2021-11-25 11:46
That is super interesting. I need to investigate futher.

**Comment by Spiritreader** [comment] 2022-10-24 12:14
I still can't reproduce this, but we may have found the reason for the crash. It should correctly show an error box now instead of crashing that can potentially tell us more.

**Comment by Spiritreader** [comment] 2023-02-05 22:01
should be fully fixed with [#69a413](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/commit/69a413485aa02a8dfcd9d50bb3e1ee7ad0a1d967)

**Closed by Spiritreader** 2023-02-05 22:01 UTC
Labels: bug, can't reproduce
