### ISSUE TITLE
Top-shelf app. One thing missing: Hot key / keyboard shortcut

### ISSUE THREAD

**Issue by anth11** [AutoDarkMode/Windows-Auto-Night-Mode#354] opened 2021-11-05 12:23 UTC
Would be nice if users can use hotkeys to enable or disable dark mode.

Additionally, to be able to use a custom keyboard shortcut for that.

**Comment by Armin2208** [comment] 2021-11-05 19:17
duplicate of #5

**Closed by Armin2208** 2021-11-05 19:17 UTC
Labels: enhancement
