### ISSUE TITLE
Offset settings don't work in the "Follow Windows night light" option.

### ISSUE THREAD

**Issue by cmhrky** [AutoDarkMode/Windows-Auto-Night-Mode#563] opened 2022-10-16 19:01 UTC
### Description

Offset settings don't work. ADM switches the theme at the time in Windows night light settings (From sunset to sunrise).

### Expected Behavior

I do not use the "Follow Windows night light" option, but when I tried it, I saw that the offset settings did not work.

If offset settings cannot be made, this option can be completely hidden from this section.

### Log Data

[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9795460/config.yaml.txt)
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9795461/service.log)

### Operating System

Windows 10 21H2 19044.2130

### Commit Hash and Version

- Commit: `a32bc01`
- Service: `10.3.0.51`
- Updater: `2.5.1`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.10`

**Comment by cmhrky** [comment] 2022-10-16 19:14
Also in Windows 10 LTSC 1809 version 17763.3532 it behaves as in the video and on next reboot "AutoDarkModeSvc.exe" does not work.


https://user-images.githubusercontent.com/17867666/196053584-d12cfcfc-93c3-4b2f-b6e0-18343c3e0e16.mp4

**Comment by Spiritreader** [comment] 2022-10-16 21:03
A thing to understand about Night Light.
We only have information about:
- when night light is turned off/on
- If it is turned off/on

For that reason, negative offsets can't work. I'll update the UI to reflect this.
The issue you had with it immediately switching when you hit set was because the internal night light state is currently propagated outwards. This is actually intended behavior and functioning correctly, however I can see that it is a bit confusing.
I will change this such that modifying the offset will not affect the immediate UI switching behavior.
Please note that this as a result means that changing the offset will take up to 1 minute to propagate as that is the internal update rate of the nightlight tracker module.

______

As far as the crashing is concerned. I don't really have Win10 LTSC and the feature in itself is only meant for Win10 21H2 and upwards, so I can't guarantee that this will be fixed.

**Comment by cmhrky** [comment] 2022-10-17 13:56
For LTSC there is no problem anymore and "AutoDarkModeSvc.exe" starts fine. But when I tried it, it didn't work even when there was a positive light offset. I also set it to 0 and the problem is no more.

Likewise, for 21H2, the positive light offset needs to be set to 0. Otherwise it switches to dark theme after a minute.

**Comment by Spiritreader** [comment] 2022-10-17 14:06
> Likewise, for 21H2, the positive light offset needs to be set to 0. Otherwise it switches to dark theme after a minute.

I can't reproduce that. If I change the offset in the newer builds nothing will happen, except when the trigger time exceeds the offset time.

**Comment by Spiritreader** [comment] 2022-10-19 12:04
should work fine in the latest builds.

**Closed by Spiritreader** 2022-10-19 12:04 UTC
Labels: bug

**Comment by cmhrky** [comment] 2022-10-19 14:50
In 21H2, when I set the light offset to 5 minutes and restart "AutoDarkModeSvc.exe", it switches to dark mode after a few minutes. 

![nlS](https://user-images.githubusercontent.com/17867666/196725317-51fc3e86-a79b-4619-82e2-82fdb7acdf79.jpg)
