### ISSUE TITLE
The menu that opens from the notification area does not disappear

### ISSUE THREAD

**Issue by AleXDarkstalker99** [AutoDarkMode/Windows-Auto-Night-Mode#408] opened 2021-12-24 18:38 UTC
**Description**

If you click on the icon from the notification area first LMB, then RMB, it will not disappear intil you do not click on one of the menu items

**Expected behavior**

If you click just RMB, there is no such problem

**Log Data**

**Commit Hash and Version**

- Commit: `22e2298`
- Service: `10.1.1.4`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.0`

**Screenshots**

![Снимок экрана (3)](https://user-images.githubusercontent.com/96627318/147368878-b666f89b-3451-4d86-bfc6-cdcdee68353e.png)

**Comment by AleXDarkstalker99** [comment] 2021-12-27 18:39
Programs should be open on task panel

**Comment by Armin2208** [comment] 2021-12-27 21:04
ah got it!

**Comment by Armin2208** [comment] 2021-12-27 21:04
this is microsofts implementation of tray lol

**Comment by tooomm** [comment] 2022-03-25 10:48
I can not reproduce this on Windows 10:
- Commit: `b5ae91f`
- Service: `10.1.1.8`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.1`

**Comment by Spiritreader** [comment] 2022-10-01 17:22
Also can't reproduce. Will categorize this as wontfix for now due to its very low impact on functionality. It may eventually be fixed as a side-effect once we switch frameworks.

**Closed by Spiritreader** 2022-10-01 17:22 UTC
Labels: bug, framework
