### ISSUE TITLE
file explorer not changing to dark mode in windows 11 dev version

### ISSUE THREAD

**Issue by zhenjie1999** [AutoDarkMode/Windows-Auto-Night-Mode#424] opened 2022-02-19 11:12 UTC
**Description**
file explorer not chaging to dark mode in windows 11 dev version
I already check not delay problem, all UI already change but only file explorer not chaging at all
updated to auto night mode beta version also same
**Expected behavior**
only file explorer not chaging, but can change it using windows setting theme section

**Log Data**
[C-Users-zhenj-AppData-Roaming-AutoDarkMode.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8102453/C-Users-zhenj-AppData-Roaming-AutoDarkMode.zip)
[config and service.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/8102454/config.and.service.zip)

**Commit Hash and Version**

**Screenshots**

**Comment by WindowsTablet** [comment] 2022-02-19 12:59
Same issue here. Also, Taskbar does not change here.

**Comment by Spiritreader** [comment] 2022-02-19 14:45
Without providing the full log and config data, we can't really look into it.
Also, since it is a Windows 11 dev build, things may be subject to change or broke

**Comment by zhenjie1999** [comment] 2022-02-19 15:18
attashed require file, pls check tq

**Comment by Spiritreader** [comment] 2022-02-19 16:46
Okay from what I can tell (without actually having access to the win11 dev build) it seems like there is a new registry key for the explorer, or that it doesn't get updated properly if the regkey changes.

Unfortunately we'll have to wait until this becomes an issue in mainstream builds or @Armin2208 checks it out on another Win11 test machine.

**Comment by Armin2208** [comment] 2022-02-19 19:36
Confirmed this behaviour on my test machine. Thme switch is now in general really broken. The explorer doesn't switch and the taskbar only changes its theme after opening the startmenu. And even after that the text doesn't adapt, so it gets unreadable.

Because this is a dev build we will not work on a fast fix. We need to watch to further changes of Microsoft, because they seem like to revamp their theme switch mechanic right now. Probably the work has not ended yet. It wouldn't be worth it to push an update for 22557 just to get a different behavior with the next build.

**Comment by Spiritreader** [comment] 2022-02-19 20:14
> Confirmed this behaviour on my test machine. Thme switch is now in general really broken. The explorer doesn't switch and the taskbar only changes its theme after opening the startmenu. And even after that the text doesn't adapt, so it gets unreadable.
> 
> Because this is a dev build we will not work on a fast fix. We need to watch to further changes of Microsoft, because they seem like to revamp their theme switch mechanic right now. Probably the work has not ended yet. It wouldn't be worth it to push an update for 22557 just to get a different behavior with the next build.

Thanks for investigating! Yea I think watching the changes for now is the correct way to deal with this

**Comment by Armin2208** [comment] 2022-02-20 01:10
A workaround for now would be to use Windows .Theme-File switch under personalization. So create one theme for dark mode and one theme for light mode in Windows settings. And then let Auto Dark Mode switch them for you :)

**Comment by Ir0ngin** [comment] 2022-03-24 07:16
Just to let you know that Microsoft pushed update 22581 into beta status yesterday. The new theme switch mechanism is probably discontinued now.

**Comment by chuck00000** [comment] 2022-03-27 10:01
please update this app , the stupid microsoft still don't want to add an option schedule times automatically switch  light/dark appearance, light/dark switch didn't normal is very annoying

**Comment by wfsg00098** [comment] 2022-03-28 12:02
theme mode still works

**Comment by voldemort2826** [comment] 2022-03-31 03:13
It seems like restarting explorer.exe helps, but having to do that manually is kinda defeat the purpose of the program

**Comment by toastytortilla** [comment] 2022-04-13 21:11
Hey guys, thank you so much for this awesome piece of software. Using it has been a blast.

I see that you're (intelligently) waiting until Win11 builds stabilize to do a proper fix, so if anyone is still encountering this specific problem it seems that restarting Explorer from Task Manager fixes the issue. I'm running build 22593 for reference.

**Comment by Spiritreader** [comment] 2022-04-13 22:45
> Hey guys, thank you so much for this awesome piece of software. Using it has been a blast.
> 
> I see that you're (intelligently) waiting until Win11 builds stabilize to do a proper fix, so if anyone is still encountering this specific problem it seems that restarting Explorer from Task Manager fixes the issue. I'm running build 22593 for reference.

@toastytortilla  So far, it sadly appears like Microsoft is not intending to make the old theme switch option work again the way it had before for the next stable build.

Auto Dark Mode also supports arbitrary script automation in the latest beta builds, so if you really wanted to use the registry-key based theme switch option at the moment, you could let ADM auto restart your explorer.
See here for more info https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts

Concerning what we are going to do, tough call. Either disable the older theme switch mechanism as a whole, or introduce >=22593 specific behavior that auto restarts the explorer. None of these are "good" solutions, but we'll have to continue monitoring the situation.

**Comment by toastytortilla** [comment] 2022-04-18 22:13
@Spiritreader So I was about to start toying with the registry-key edits when I noticed that the problem seemed like it had solved itself... I'm not sure how. The only thing I changed in ADM was enabling Windows Theme Switch with two different themes. It has completely fixed the taskbar issue.

**Comment by SubjunctiveQuaver** [comment] 2022-04-19 08:11
Awesome! Will there be a fix for this soon?

**Comment by SubjunctiveQuaver** [comment] 2022-04-21 13:59
Hmm, but is that possible to combine with the Windows Spotlight feature? You can't save that as a theme from what I've found -- it only saves one particular image. That's the only reason why I'm not already using themes (I was before when I had a fixed background).

**Comment by wfsg00098** [comment] 2022-04-21 14:30
maybe this should be done by microsoft



发送自我的盖乐世



-------- 原始信息 --------
发件人： Lawrence Chen ***@***.***>
日期: 2022/4/21 22:00 (GMT+08:00)
收件人： AutoDarkMode/Windows-Auto-Night-Mode ***@***.***>
抄送： 王悄悄 ***@***.***>, Comment ***@***.***>
主题： Re: [AutoDarkMode/Windows-Auto-Night-Mode] file explorer not chaging to dark mode in windows 11 dev version (Issue #424)


Hmm, but is that possible to combine with the Windows Spotlight feature? You can't save that as a theme from what I've found -- it only saves one particular image. That's the only reason why I'm not already using themes (I was before when I had a fixed background).

―

**Comment by Spiritreader** [comment] 2022-04-21 17:43
> Hmm, but is that possible to combine with the Windows Spotlight feature? You can't save that as a theme from what I've found -- it only saves one particular image. That's the only reason why I'm not already using themes (I was before when I had a fixed background).

In theory it is still possible to preserve the wallpaper switching functionality. It will come with some drawbacks, because we would have to switch the theme first and then re-apply the wallpapers.
We will have to investigate how to support this.

Until the next stable version of windows 11 is released, there won't be any changed to auto dark Mode though.

**Comment by hellodit** [comment] 2022-04-26 21:19
Using switch themes based worked for me

**Comment by Spiritreader** [comment] 2022-05-17 13:27
This should be fixed in the latest beta (10.2.0.0), however, please note that the taskbar accent color will remain broken as it is no longer possible to switch it in the latest Win11 builds without using the control panel directl.y

Please test out if all the other inconsistencies are fixed now though.
Thanks!

**Comment by chuck00000** [comment] 2022-05-18 13:07
> This should be fixed in the latest beta (10.2.0.0), however, please note that the taskbar accent color will remain broken as it is no longer possible to switch it in the latest Win11 builds without using the control panel directl.y
> 
> Please test out if all the other inconsistencies are fixed now though. Thanks!

Er, just the theme switch basically, ADMTheme generated.

**Comment by yell0wsuit** [comment] 2022-05-29 01:24
I also have this issue, restarting explorer.exe fixes the problem but you will lose the opened explorer windows. So save them or use other file managers.

Script in `scripts.yaml` to restart explorer for the time being.

```
Enabled: true
Component:
  TimeoutMillis: 10000
  Scripts:
  - Name: cmd example
    Command: cmd
    WorkingDirectory: %AppData%\AutoDarkMode
    ArgsLight: [/c, taskkill /F /IM explorer.exe & start explorer.exe]
    ArgsDark: [/c, taskkill /F /IM explorer.exe & start explorer.exe]
    AllowedSources: [Any]
```

**Comment by Armin2208** [comment] 2022-05-30 19:25
please update to the newest beta version of Auto Dark Mode and try our fix for Insider Builds. Thx!

**Comment by yell0wsuit** [comment] 2022-05-31 13:07
Seem like the latest beta 10.2.0.6 works flawlessly for Insider builds, at least for now. I'm using Beta channel btw.

**Comment by ZMYaro** [comment] 2022-06-14 01:40
In the latest Windows 11, in addition to this issue, the Auto Dark Theme window itself only partially changes:
https://user-images.githubusercontent.com/763405/173475318-7fdfe3e1-e76b-47e4-9a26-3b2f9e114c2d.mp4

**Comment by Spiritreader** [comment] 2022-06-14 11:18
> In the latest Windows 11, in addition to this issue, the Auto Dark Theme window itself only partially changes:
> 
>  auto_dark_mode_win11.mp4

Need to look into whether the UI framework can be updated. If not, sadly nothing we can do abt it for now.

**Comment by Armin2208** [comment] 2022-06-14 20:23
> In the latest Windows 11, in addition to this issue, the Auto Dark Theme window itself only partially changes:

btw you arent joined auto dark mode beta channel to receive the 22h2 fix

**Comment by ZMYaro** [comment] 2022-06-15 02:50
Oh, I missed that that fix was out on the beta channel; thanks!  It looks like the file explorer issue still happens there, but it does fix some of the other issues!

**Comment by Spiritreader** [comment] 2022-06-15 09:43
> Oh, I missed that that fix was out on the beta channel; thanks! It looks like the file explorer issue still happens there, but it does fix some of the other issues!

Yeah the explorer issue seems to unfortunately be here to stay for a while until MS fixes it.

**Comment by Armin2208** [comment] 2022-06-15 19:15
Microsoft has acknowledged our file explorer issue
![image](https://user-images.githubusercontent.com/32982430/173906732-4418cbbd-38e3-4485-8706-3720632f641d.png)

**Comment by Spiritreader** [comment] 2022-06-16 09:42
> Microsoft has acknowledged our file explorer issue - kinda ![image](https://user-images.githubusercontent.com/32982430/173906732-4418cbbd-38e3-4485-8706-3720632f641d.png)

Well, *one* of the issues, but sadly not the one that is causing the most inconsistency. Hopefully that one will get fixed as well at some point.

**Comment by yell0wsuit** [comment] 2022-06-20 00:55
Seem like beta 10.2.0.8 breaks dark/light theme switching. 10.2.0.7 worked fine before.

**Comment by GitStudying** [comment] 2022-07-11 20:06
So as @Spiritreader said, it has more to do with windows dev/beta build itself not implementing the change properly than the auto dark mode switching. However, it is not a perfect solution but setting system to accent only inside of 'applications' tab and then accent only > light theme. Gives me quite wanted behavior (explorer turning fully dark when switched automatically) and does not result in the buggy explorer. Not sure why.

**Comment by drandarov-io** [comment] 2022-09-19 07:45
Just want to confirm that the workaround with the theme switching still works as of build 22621.521 where I had the same problem with the taskbar not switching or the text being the wrong color.

![image](https://user-images.githubusercontent.com/13102251/190971376-8da16b78-5c0c-4beb-a73d-fe005dac8512.png)

**Comment by UMOAQ** [comment] 2022-09-22 10:37
I also have this problem in windows 11 version 2022 H2, Last updated yesterday! @Spiritreader

**Comment by UMOAQ** [comment] 2022-09-22 10:39
> Just want to confirm that the workaround with the theme switching still works as of build 22621.521 (22H2), because this issue hasn't been updated in a while. I had the same problem with the taskbar not switching or the text being the wrong color.
> 
> ![image](https://user-images.githubusercontent.com/13102251/190971376-8da16b78-5c0c-4beb-a73d-fe005dac8512.png)

Yes, this method works, but I want to use ADM combine with windows desktop dynamic to change the wallpaper auto for many     
times a day. And change the theme can't fit it.

**Comment by Spiritreader** [comment] 2022-09-22 10:50
Since 22H2 is out now:

Anything at this point is unfixable by us and a Windows problem.
We will attempt to mitigate if possible, but no guarantees, no ETA.

MS broke it, it's up to them to fix it. We can only do so much at this point unfortunately.

There are a few things we can probably fix (wallpapers not switching correctly), but **anything** related will remain broken unless MS fixes their theme switch.

**Comment by drandarov-io** [comment] 2022-09-22 10:55
@Spiritreader Is there an issue in the feedback hub? Maybe it'd make sense to consolidate the feedback here and forward people to the feedback hub from here and/or a known issues section in the README.

**Comment by Spiritreader** [comment] 2022-09-22 10:59
I think @Armin2208 reported the issues during insider, it's a great idea to put up a README.
We'll probably do that as soon as we know the full extent of issues with 22H2 and our 10.2.x releases to avoid that we accidentally declare an ADM bug as Windows issue.

**Comment by Spiritreader** [comment] 2022-09-26 18:27
> Awesome! Will there be a fix for this soon?

Soon on stable builds is now.

**Comment by Spiritreader** [comment] 2022-10-05 11:50
On our end, this is fixed as best as we can.
Any other changes need to be done by Microsoft.

Therefore marking this as closed/completed

**Closed by Spiritreader** 2022-10-05 11:50 UTC
Labels: bug, more info required
