### ISSUE TITLE
Wallpaper changes for a second, then goes back to default Windows wallpaper

### ISSUE THREAD

**Issue by Randomaker** [AutoDarkMode/Windows-Auto-Night-Mode#878] opened 2024-09-20 15:19 UTC
### Description

Hello! I recently started having an issue with Auto Dark Mode not changing my wallpaper correctly. I did upgrade to Win 11 recently, I don't remember if this problem started happening at the same time or not. I have a different wallpaper set in AutoDarkMode light and dark. However, whenever the theme switches, either manually or automatically, it shows the correct wallpaper for a fraction of a second before switching back to whatever wallpaper is set in Windows settings. I'm not sure if this is because I have something set incorrectly on my side or if it's a bug, but it used to work perfectly fine.

### Log Data

[autodarkmode-logdata.zip](https://github.com/user-attachments/files/17077169/autodarkmode-logdata.zip)

### Commit Hash, Version and Windows Build

Commit cf7a0fe
App/Service 10.4.1.1
Windows 22631.4169

**Comment by PhilippeBruno** [comment] 2024-09-25 20:08
I have the exact same problem on my Windows 11 machine. In my case, it never worked as intended.

**Comment by LeonYew-SWPU** [comment] 2024-09-29 02:50
Similar problem, but in my case, the wallpaper will be stuck on the previous wallpaper and will not switch automatically unless I manually click the check box to switch pictures (it seems that this will call up the function).

**Comment by Spiritreader** [comment] 2024-10-03 12:23
this is a known issue that should be fixed in the beta version

**Comment by EliasOS** [comment] 2024-10-18 08:00
I have the same problem and also, since I use multiple desktops, the theme seems to alternate, very strange. (Right now I'm using the dark theme)
![image](https://github.com/user-attachments/assets/6e4873fc-1b54-4cfe-a582-80ff7ef2c5cb)

**Comment by blm768** [comment] 2024-10-24 23:59
I think the issue with multiple desktops is tracked in #469.

**Comment by Armin2208** [comment] 2024-10-30 16:32
Sorry for the delayed update, but we are really trying to get it as fast as possible out.

**Closed by Armin2208** 2024-10-30 16:32 UTC
Labels: needs triage
