### ISSUE TITLE
Allow to temporarily switch theme/mode for e.g. today / Prepone activation on demand

### ISSUE THREAD

**Issue by tooomm** [AutoDarkMode/Windows-Auto-Night-Mode#439] opened 2022-03-25 10:20 UTC
**Describe the enhancement or feature you'd like**
![Untitled](https://user-images.githubusercontent.com/9874850/160099169-306bf673-a53d-47a1-bfb6-0e9e22d5569d.png)
There are only permanent toggle buttons which override your custom schedule. While there are use cases for this, there are other situations where one only wants to enable Dark Mode according to a specific environment they are currently working in.
It would be a great if the tool supports the user here and automatically goes back to his selected schedule.

It could be a combined button which temporarily enables the mode which is currently not running, e.g.
`Enable Light/Dark Theme for Today`
Enabling a certain mode until next (scheduled) execution would also describe the requested action.

Such a feature would basically prepone the planned schedule activation on request once, without altering the schedule itself and goes back to normal behavior on the selected times.

<br>

(BTW: If you want to take a screenshot, the enabled check marks in that menu never shop up in the screenshot on Win 10 😄)

**Comment by Spiritreader** [comment] 2022-10-06 00:18
IT'S HERE!!!

UI Implementation in the app is still a work in progress, but the rest is available starting with 10.3.0.12

**Comment by Spiritreader** [comment] 2022-10-06 14:42
![admtogglespostponedemo](https://user-images.githubusercontent.com/18438899/194343078-ff2d4dbb-2f27-4fb7-b762-542c7946ad39.gif)

![image](https://user-images.githubusercontent.com/18438899/194343114-b942e9d7-e7b0-47fa-9e14-c5c3d38b624f.png)

**Comment by tooomm** [comment] 2022-10-08 15:49
Hi @Spiritreader, those a great news! Thanks for the update and working on this.

Regarding the tray menustrip options:
Currently, you show check marks as well as completely change the display name of the option when selected/enabled.
`[_] Skip next switch` and `[✓] Resume switch (paused until 18:43)` from your example above.
 I think a check mark works best to show if something is enabled or not. But if you change the title completely (adding some information is fine), the connection to the option is lost for the user. Changing a label completely works well with a toggle button for example, but not so much here.
To keep things simple and intuitive I suggest to try something like 
`[_] Skip next switch` (not selected, disabled) and `[✓] Skip next switch (18:43)` (selected, enabled). The time of the next scheduled switch could also be shown when the option is not enabled to clearly tell the user which switch is going to be skipped! `[_] Skip next switch (18:43)`, or make it more verbose like
`[_] Skip next switch to dark (at 18:43)`
`[_] Skip next switch to light (at 7:00)`


<br>

Besides the UI suggestion, I'm just not sure if things are working as they should for me on Windows 10 with v10.3.0.23 at all... 🙈 

1) Let's say it's 17:00 o'clock, I put dark mode to start at 17:02. I then select `Skip next switch` from the tray icon. The check mark appears and the text changes to `Resume switch (paused until 17:02)`. Then, at 17:02 it switches to dark mode, the menu option changes back to `Skip next switch` (and the check mark disappears)... but shouldn't it skip that switch?! 🤔 
I then tried the same with light mode and put it to start at 17:10 and dark mode to 20:00 and told it to skip the next switch. Same result: The switch still occurs and the skip feature does not work respectively.

2) I see in your video, there is a `Show notification on toggle` option and a notification shows up on Windows 11. That's not the case on Windows 10 for me.

<br>

>Note: the feature we're tackling here is strictly postponing theme switch until the next day (next switch interval)
Skipping for a fixed amount of time will be tackled in https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/204

:+1:

**Comment by Spiritreader** [comment] 2022-10-09 16:53
Hey Tom, long time no see
Appreciate your thorough testing!

> I think a check mark works best to show if something is enabled or not. 

I do understand the appeal of what you have proposed, but I will just remove the checkmark for the skip entry will be removed so it behaves like the toggle button. The postpone menu entry is technically a toggle, so I will just keep the text changes intead.

> I see in your video, when the Show notification on toggle option is selected, 

Notification is only shown when using hotkeys. Haven't decided yet whether that will change.

>  I'm just not sure if things are working as they should for me

They definitely are working like they should. It's just thta how things work currently are correct for all scenarios.
There's more of a miconfiguration. The entry you can hit in the notification misbehaves in one particular situation:
It works the same as the postpone that is induced when using the toggle theme hotkey.

That one expires one second after the next theme switch trigger time.
So for example, sunset is at 18:00, and current time is 16:00. User hits "toggle theme" and the theme switches to dark. The postpone is engaged until 18:00:01 and once it expires the system finds itself correctly in the dark state again.

However as you've spotted correctly, when someone *just* wants to postpone the theme without switching, it needs to be moved ahead one more switch. Thanks for pointing that out, did miss that.
In that case that also introduces the necessity for one more hotkey to toggle that version of postpone off and on.

Logic is the same on both OS versions.

**Comment by tooomm** [comment] 2022-10-09 17:30
Always a pleasure to help with improving a great tool even further! ;)

<br>

>The postpone menu entry is technically a toggle, so I will just keep the text changes instead.

As long as you remove the check mark when going for the toggle style it should remove potential confusion for users. 👍

> Notification is only shown when using hotkeys. Haven't decided yet whether that will change.

Ahh, was not aware of that. When using hotkeys, the notification shows up on Windows 10 for me as well!

<br>

Definitely looking forward to the next beta releases!

**Comment by Spiritreader** [comment] 2022-10-10 00:50
> As long as you remove the check mark when going for the toggle style it should remove potential confusion for users. 👍

Yea scratch what I said. I tried multiple options without the checkmark and that was even more confusing because it logically clashes with the auto switching entry above it. 
I've resorted to a hybrid approach of how it was before and what you suggested.
In addition, when auto theme switching is disabled, the pause/postpone entry now gets hidden.

The logic oversight you pointed out is now fixed (turned out that was MUCH **much** worse and more difficult to get right than a bug could've ever been...)

It now correctly detects the scenario of wanting to stay in the current theme by extending the postpone properly, but still keeps the toggle logic the same.
Also the windows night light mode *does* show some information now, but it's not more than sunset/sunrise because it's not possible to extract precise time data from the binary blob.

New hotkey has also been added with a toggleable notification.

**Comment by tooomm** [comment] 2022-10-10 20:42
Quick feedback:
- The first button should probably be labeled `Toggle now` or `Switch theme`?
![not](https://user-images.githubusercontent.com/9874850/194944798-d5742dc7-603e-410b-8114-c219ceffbe60.png)
The text should also align with the label better. A confirm button for switching immediately does not work well here IMHO.

- The "skip" logic works now, the check mark while preserving the option label is easy to understand as well. Nice addition with hiding the pause option when automatic switching is disabled! 👌

- I still think the wording on the label can be improved. Maybe it's just me, but telling the user to pause something until e.g. 21:00, when it's shortly after 21:00 can be a bit puzzling:
![pause](https://user-images.githubusercontent.com/9874850/194945553-ae088686-4b76-482b-9976-e26bda09bac5.png)
I get the idea behind it, but the time value doesn't really add too much and leaves room for misinterpretation.
Do you see any disadvantage or shortcoming when using a more simple label like `Skip next activation`, `Pause for today`, `Keep current theme for today` or `Use current theme until tomorrow` etc?

**Comment by Spiritreader** [comment] 2022-10-10 20:49
> The first button should probably be labeled Toggle now or Switch theme?

There are no translation strings yet for the butons. This will come at some point in the future

> 21:00, when it's shortly after 21:00 can be a bit puzzling:

Nothing will change in that regard. People will just have to use a bit of brain for that one.
"today" and "tomorrow" doesn't work because it doesn't imply which of the 2 switches in a day are triggered.

**Comment by tooomm** [comment] 2022-10-15 16:27
After using it for a while, I like your solution and that you only add the day when it's not the same day. 👍 

When following Windows night light, the tray menu uses the nice term `(until next sunset)`/`(until next sunrise)`.
The same should be used for both "sunset to sunrise" options instead time values as well in my opinion.

**Comment by Spiritreader** [comment] 2022-10-15 17:43
I'm quite happy with where it's at eight now, the version you're seeing is final.

**Comment by tooomm** [comment] 2022-10-15 18:13
Just saying... Users that explicitly chose to use a dynamic event based on their location over a specific time value probably care about the sun, not the time.

**Closed** 2022-10-21 02:29 UTC
Labels: enhancement

**Comment by skaiteo** [comment] 2022-10-28 08:50
> ![admtogglespostponedemo](https://user-images.githubusercontent.com/18438899/194343078-ff2d4dbb-2f27-4fb7-b762-542c7946ad39.gif) [ ![admtogglespostponedemo](https://user-images.githubusercontent.com/18438899/194343078-ff2d4dbb-2f27-4fb7-b762-542c7946ad39.gif) ](https://user-images.githubusercontent.com/18438899/194343078-ff2d4dbb-2f27-4fb7-b762-542c7946ad39.gif) [ ](https://user-images.githubusercontent.com/18438899/194343078-ff2d4dbb-2f27-4fb7-b762-542c7946ad39.gif)
> 
> ![image](https://user-images.githubusercontent.com/18438899/194343114-b942e9d7-e7b0-47fa-9e14-c5c3d38b624f.png)

Noticed the "Toggle theme" option here. I can't find any mention of it in other issues, commits or PRs, is this already implemented or still in development?

**Comment by skaiteo** [comment] 2022-10-28 08:52
Hey @Spiritreader, I noticed the "Toggle theme" option here. I can't find any mention of it in other issues, commits or PRs, is it already implemented or is it being developed together with this feature request?

**Comment by Spiritreader** [comment] 2022-10-28 09:05
> Hey @Spiritreader, I noticed the "Toggle theme" option here. I can't find any mention of it in other issues, commits or PRs, is it already implemented or is it being developed together with this feature request?

Yes it's implemented and available in the latest beta versions of Auto Dark Mode.

**Comment by Spiritreader** [comment] 2022-10-28 12:51
> Awesome! Is stable 10.3.0 is releasing any time soon?

The current beta version is the stable RC. Functionally they're the same. We're running a testing phase at the moment to ensure no unexpected behavior shows up
