### ISSUE TITLE
Auto-Night Thinks Device is Unplugged

### ISSUE THREAD

**Issue by Eymay** [AutoDarkMode/Windows-Auto-Night-Mode#399] opened 2021-12-11 07:19 UTC
I use an Asus laptop which has a feature to limit the battery percentage when plugged. I also want to use the 'Night Mode when unplugged' feature but when the limit is reached Auto Night Mode thinks device is unplugged and reverts to Night mode. Is there a way to implement this?

**Comment by Spiritreader** [comment] 2021-12-12 00:29
duplicate of https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/386

**Closed by Spiritreader** 2021-12-12 00:29 UTC
Labels: enhancement
