### ISSUE TITLE
Add an option to use "Show accent color on title bars and window borders" in dark mode

### ISSUE THREAD

**Issue by WindowsTablet** [AutoDarkMode/Windows-Auto-Night-Mode#373] opened 2021-11-13 19:02 UTC
Add an option to use "Show accent color on title bars and window borders" in dark mode, so that certain apps with legacy controls get dark themed properly, without being forced to use that option for the light theme.

Thanks in advance.

**Comment by Spiritreader** [comment] 2021-11-14 23:04
duplicate of #219

**Closed by Spiritreader** 2021-11-14 23:04 UTC
Labels: enhancement
