### ISSUE TITLE
Time zone change not followed

### ISSUE THREAD

**Issue by juhaszp95** [AutoDarkMode/Windows-Auto-Night-Mode#725] opened 2023-05-14 19:20 UTC
### Description

My Auto Dark Mode is set to automatically enable dark mode at 9pm. I would like this to be done at 9pm local time (what is displayed by Windows), whatever that is. However, I'm travelling and I changed my time zone (setting the clock an hour ahead), and the theme switch now happens at 8pm (which is 9pm at the place where I originally set my settings). I need to change my Auto Dark Mode settings to 10pm to make the switch happen at 9pm local time - i.e. it's as if Auto Dark Mode didn't realise that the Windows time was updated to match the new time zone.

### Expected Behavior

Auto Dark Mode should use the time provided by Windows for fixed-time theme switching. It should detect if the Windows time is updated, e.g. due to a change in time zone.

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11472747/service.log)
[config.yaml](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11472748/config.yaml.txt)

### Commit Hash, Version and Windows Build

- Commit: `212dbb4`
- Service/App: `10.3.0.90`
- Updater: `2.5.2`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `22621.1702`

**Comment by Spiritreader** [comment] 2023-05-15 21:05
Time zone changes are currently not supported because c# by default prevents that in order to preserve time-critical operations and a restart of the application is required.

This is, at the moment, intended behavior.

Please see here for more details:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/discussions/704#discussioncomment-5582730

However, I've been already testing this new functionality allowing for time zone changes on this branch which may get merged for the next release.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/tree/timezones

**Closed as completed** 2023-05-17 12:58 UTC
