### ISSUE TITLE
Add lockscreen wallpaper to Wallpaper Switch

### ISSUE THREAD

**Issue by SlowNicoFish** [AutoDarkMode/Windows-Auto-Night-Mode#789] opened 2023-10-19 22:55 UTC
**Describe the enhancement or feature you'd like**
It would be very nice of the lockscreen could also be changed based on dark/light mode.
I do not know if this is possible but it would be nice to have.

**Comment by Spiritreader** [comment] 2023-10-23 20:18
duplicate of #637

**Closed by Spiritreader** 2023-10-23 20:18 UTC
Labels: enhancement
